config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'
  
  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
  reject_if: lambda { |attrs| attrs['name'].blank?}
  include Placeholder
  validates_presence_of :title, :body
  #the self refers to an indvidual item, portfolio 
  def self.angular
    where(subtitle: "Angular")
  end
  #same as the above
  scope :ruby_on_rails_portfolio, -> { where(subtitle: "Ruby on Rails") }
  
  after_initialize :set_defaults 
  
  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end
  

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
   before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  
  def index
    @portfolio_items = Portfolio.all 
  end
  
  def new 
   @portfolio_item = Portfolio.new 
    #3.times {@portfolio_items.technologies.build } 
  end
  
  def create
     @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def edit
   # @portfolio_item = Portfolio.find(params[:id])
  end
  
  def update
    #@portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  
  def show
   #@portfolio_item = Portfolio.find(params[:id])
  end
  
  def destroy
     @portfolio_item = Portfolio.find(params[:id])
     @portfolio_item.destroy
     respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully removed.' }
     end
  end
  private
  
  def set_portfolio
      @portfolio_item = Portfolio.friendly.find(params[:id])
    end
  
   def portfolio_params
       params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body,
                                        )
    end
     
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/angular.html.erb
<h1>Angular portfolio Items</h1>
<%= link_to 'Create new item', new_portfolio_path %>

<% @angular_portfolio_items.each do |items| %>
<p><%= link_to items.title, show_portfolio_path(items) %></p>
<p><%= items.subtitle %></p>
<p><%= items.body %></p>
<%= link_to image_tag(items.thumb_image), show_portfolio_path(items) unless items.thumb_image.nil?%>
<%= link_to 'Edit', edit_portfolio_path(items) %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>

<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
    <%= link_to 'Back', portfolios_path %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>
<%= link_to 'Create new item', new_portfolio_path %>

<% @portfolio_items.each do |items| %>
<p><%= link_to items.title, show_portfolio_path(items) %></p>
<p><%= items.subtitle %></p>
<p><%= items.body %></p>
<%= link_to image_tag(items.thumb_image), show_portfolio_path(items) unless items.thumb_image.nil?%>
<%= link_to 'Edit', edit_portfolio_path(items) %>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new portfolio item</h1>

<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<h1><%= @portfolio_item.title %></h1>
<h2><%= @portfolio_item.subtitle %></h2>
<p><%= @portfolio_item.body %></p>
<%= image_tag @portfolio_item.main_image %>
<%= link_to 'Edit', edit_portfolio_path %>
<p><%= link_to 'Back', portfolios_path %></p>
<p><%= link_to 'Delete', @portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %>